version: '3'
services:    
  st-mysql:
    container_name: st-mysql
    build:
      context: ./
      dockerfile: ./docker/st-mysql/Dockerfile
    environment:
      MYSQL_DATABASE: st
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_ROOT_HOST: '%'
      TZ: Asia/Shanghai
    expose:
    - "3306"
    restart: always

  st-job:
    container_name: st-job
    build:
      context: ./
      dockerfile: ./docker/st-job/Dockerfile
    environment:
      TZ: Asia/Shanghai
      DB_USER: root
      DB_PASSWORD: 123456
    volumes:
    - ./logs:/code/log/
    ports:
    - "8080:8080"
    depends_on:
    - st-mysql
    restart: always


    